# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20170130_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Concise text suggested.', verbose_name='tease'),
        ),
    ]
