# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20170130_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Concise text suggested.', verbose_name='excerpt'),
        ),
    ]
