# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:49
from __future__ import unicode_literals

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20170327_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=baseapp.models.getNow, verbose_name='publish'),
        ),
    ]
