# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20170327_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='slug'),
        ),
    ]
